---
name: Build
"on":
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  schedule:
    - cron: "5 8 * * 1"

jobs:
  # Ensure the image builds and ansible is installed.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout.
        uses: actions/checkout@v2

      - name: Build the image.
        run: docker build -t ubuntu2004-systemd-ansible .

      - name: Create a container from the built image.
        run: docker run --name instance -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro ubuntu2004-systemd-ansible

      - name: Verify systemd is working.
        run: docker exec --tty instance systemctl list-unit-files --no-pager

      - name: Verify Ansible is working.
        run: docker exec --tty instance ansible --version

  # Build and push the image to Docker Hub.
  build-n-push:
    name: Build and push to Docker Hub.
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU.
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx.
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository }}:latest
